name: Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        run: az acr login --name emsapplication --username ${{ secrets.AZURE_USERNAME }} --password ${{ secrets.AZURE_PASSWORD }}

      - name: Building docker image
        run: docker build -f EMS.Api/Dockerfile --force-rm -t emsapplication.azurecr.io/emsapplicationcontainer123:v1 .
          
      - name: Pushing docker image
        run: docker push emsapplication.azurecr.io/emsapplicationcontainer123:v1
        
      - name: Running the docker container
        run: docker run -d -p 8080:8080 emsapplication.azurecr.io/emsapplicationcontainer123:v1
        
      - name: Azure login
        run: az account set -s "4556c0f7-1e8d-43fb-80a1-62284982e07b"
        
      - name: Create container in Azure
        run: az container create --resource-group ems-resource-group --name emsapplication --image emsapplication.azurecr.io/emsapplicationcontainer123:v1 --dns-name-label myapp --ports 8080