name: Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        run: az acr login --name emsapplication --username ${{ secrets.AZURE_USERNAME }} --password ${{ secrets.AZURE_PASSWORD }}

      - name: Building Docker image
        run: docker build -f EMS.Api/Dockerfile --force-rm -t emsapplication.azurecr.io/emsapplicationcontainer123:v1 .
          
      - name: Pushing docker image
        run: docker push emsapplication.azurecr.io/emsapplicationcontainer123:v1
        
      - name: Running the container
        run: docker run -d -p 8080:8080 emsapplication.azurecr.io/emsapplicationcontainer123:v1